#!/usr/bin/env bash
# Build "Sovereign Stack, Vol 1": markdown -> LaTeX -> PDF.
# Requires: python3 (stdlib only), pandoc, TeX Live (xelatex + latexmk), and the
# fonts TeX Gyre Pagella, TeX Gyre Heros, DejaVu Sans Mono.
#
# Editions. The book is produced in two shapes from the very same manuscript and
# machinery, A4 and A5; only the page geometry differs, and BOTH are built by
# default. The paper is a build parameter, never a second copy of the tree:
#
#   ./build.sh           # both editions (default) -> A4 and A5 in outputs/
#   ./build.sh a4        # A4 only            -> outputs/sovereign-stack-vol1.pdf
#   ./build.sh a5        # A5 only            -> outputs/sovereign-stack-vol1-a5.pdf
#   ./build.sh both      # both editions (identical to the bare default)
#
# How the paper is selected. For each edition build.sh writes src/paper.tex (the
# same generated-file pattern as src/version.tex): it sets the paper class, the
# matching \geometry call, the version-tag corner coordinates, and the
# figure-fit flag \sspaperclass that the preamble reads. The preamble \input's
# it; with no paper.tex present (a direct latexmk on a generated .tex) an A4
# fallback runs, so any .tex still builds standalone. One manuscript, one source
# of truth: the A5 variant is a parameter, not a fork that could drift.
#
# Layout produced:
#   outputs/sovereign-stack-vol1.pdf      the A4 deliverable
#   outputs/sovereign-stack-vol1-a5.pdf   the A5 deliverable (built by default; also via a5/both)
#   temp/                                 every transient build artifact, kept for review
#   temp/build.log                        a full transcript of this build (the process record)
#   <folder>.zip                          self-healing recovery snapshot (see step 4)
#
# Where the build artifacts go, and why they are kept. xelatex runs with
# -output-directory=temp, so every byproduct (the generated .tex, .aux, .log,
# .toc, .fls, .fdb_latexmk, .xdv, plus the intermediate markdown) is written
# straight into temp/ and the project root never fills with them, not even
# mid-build or after a failed run. Nothing here is deleted at the end: temp/ is
# the paper trail of the build, kept so you can review exactly what each step
# produced. Because that churn is confined to one dedicated folder, clearing it
# is a single, easy-to-oversee step that can never touch a source file:
#
#   ./build.sh clean     # show what is in temp/, then remove it (recreated next build)
#
set -euo pipefail
cd "$(dirname "$0")"                       # project root

NAME="sovereign-stack-vol1"                # base name of the A4 .md / .tex / .pdf
TEMP="temp"                                # the one folder all disk churn lives in
ARCHIVE="$(basename "$PWD").zip"           # recovery snapshot, named after the version folder

# --- ./build.sh clean : oversee, then clear, the transient folder -------------
# All build byproducts live under temp/, so reclaiming that space (or starting
# from a clean slate) is one folder and one command. We print what is there
# first, largest first, so the deletion is easy to see before it happens, and we
# only ever remove temp/ (never outputs/, never a source file).
if [ "${1:-}" = "clean" ]; then
  if [ -d "$TEMP" ] && [ -n "$(ls -A "$TEMP" 2>/dev/null)" ]; then
    echo "temp/ currently holds (largest first):"
    du -ah "$TEMP" | sort -rh
    rm -rf "${TEMP:?}"
    echo "Cleared temp/ (it is recreated on the next ./build.sh)."
  else
    echo "temp/ is empty or absent; nothing to clear."
  fi
  exit 0
fi

# --- which edition(s) to build -----------------------------------------------
# Default is BOTH editions: a bare ./build.sh always produces A4 and A5 together,
# so neither can be forgotten. Pass a4 or a5 to deliberately build just one.
case "${1:-both}" in
  a4)        PAPERS=(a4) ;;
  a5)        PAPERS=(a5) ;;
  both|all)  PAPERS=(a4 a5) ;;
  *) echo "usage: ./build.sh [a4|a5|both|clean]" >&2; exit 2 ;;
esac

mkdir -p "$TEMP" outputs

# write_paper_tex <paper> : emit src/paper.tex for the given edition.
# This is the generated file the preamble \input's. A4 reproduces the original
# geometry and tag position exactly (so the A4 book is unchanged); A5 sets the
# narrower margins, moves the version tag in to the A5 corner, and flips
# \sspaperclass to a5 so the preamble's \ssfit wrapper scales the wide diagrams.
write_paper_tex() {
  case "$1" in
    a4)
      { echo '%% generated by build.sh; do not edit by hand (regenerated each build)'
        echo '\def\sspaperclass{a4}'
        echo '\geometry{a4paper,top=2.6cm,bottom=2.5cm,left=2.7cm,right=2.7cm,headheight=15pt}'
        echo '\def\sstagx{20cm}\def\sstagy{28.7cm}'; } > src/paper.tex ;;
    a5)
      { echo '%% generated by build.sh; do not edit by hand (regenerated each build)'
        echo '\def\sspaperclass{a5}'
        echo '\geometry{a5paper,top=1.7cm,bottom=1.6cm,left=1.6cm,right=1.6cm,headheight=14pt}'
        echo '\def\sstagx{13.6cm}\def\sstagy{20.0cm}'; } > src/paper.tex ;;
  esac
}

# build_one <paper> : pandoc + xelatex for a single edition.
# The A4 edition keeps the base name; A5 gets an "-a5" suffix so its .tex/.log/
# .pdf never collide with A4's and the A4 test suite (which reads the unsuffixed
# log and PDF) keeps measuring the A4 book. Reads the shared temp/vol1_latex.md
# produced once by the preprocess step below.
build_one() {
  local paper="$1" out cls
  if [ "$paper" = "a4" ]; then out="$NAME"; else out="${NAME}-${paper}"; fi
  cls="${paper}paper"
  write_paper_tex "$paper"

  echo "[2/4] pandoc (${paper}): -> ${TEMP}/${out}.tex (preamble + title page inlined)"
  pandoc "${TEMP}/vol1_latex.md" \
    -f markdown+autolink_bare_uris -t latex -s \
    --top-level-division=chapter --listings \
    -V documentclass=report -V classoption=oneside \
    -V classoption=11pt -V "classoption=${cls}" \
    -V mainfont="TeX Gyre Pagella" -V sansfont="TeX Gyre Heros" \
    -V monofont="DejaVu Sans Mono" \
    -V colorlinks=true -V linkcolor=black -V urlcolor=blue -V toccolor=black \
    -H src/preamble.tex --include-before-body=src/frontmatter.tex \
    -o "${TEMP}/${out}.tex"

  echo "[3/4] xelatex (${paper}): -> ${TEMP}/ (PDF + byproducts in one place; images from assets/)"
  # latexmk writes every output into temp/ via -output-directory, so the project
  # root stays clean throughout the build. latexmk still runs from the project
  # root, so the relative paths the preamble uses (assets/ for images, and
  # src/version.tex / src/paper.tex) resolve exactly as before. -gg ("super go")
  # wipes latexmk's database + generated files first, forcing a full rebuild so a
  # stale .fdb_latexmk from a failed run cannot report "Nothing to do".
  latexmk -xelatex -gg -interaction=nonstopmode -halt-on-error \
    -output-directory="${TEMP}" "${TEMP}/${out}.tex"

  # The final PDF is the one artifact that leaves temp/: move it to outputs/.
  # Everything else stays in temp/ as the kept record of how it was built.
  mv -f "${TEMP}/${out}.pdf" outputs/ 2>/dev/null || true
  echo "      -> outputs/${out}.pdf"

  # Guard: the edition just built must have produced its PDF. The mv above is
  # deliberately tolerant (|| true), so without this a missing PDF would slip by
  # unnoticed. Here the whole build fails loudly instead, before the recovery
  # archive is written, so a build can never report success while silently
  # missing an edition (the exact surprise that prompted both-by-default).
  if [ ! -s "outputs/${out}.pdf" ]; then
    echo "ERROR: the ${paper} edition did not produce outputs/${out}.pdf; build failed." >&2
    exit 1
  fi
}

# Everything below is shown live and copied to temp/build.log, so each build
# leaves a full transcript of its own process beside the artifacts it produced.
{
  # --- version tag, composed from config.toml + the folder name --------------
  # config.toml holds the volume and version; the folder name holds the iteration.
  # src/mkversion.py combines them into v{volume}v{version}i{iteration}. We write
  # that into src/version.tex (which the preamble \input's) and stamp it into
  # tracker.json's "current", so the tag on every page and the tracker both follow
  # the folder with no manual edit. A direct latexmk falls back to the placeholder
  # in src/preamble.tex. Done once; both editions share the same tag.
  VERSION="$(python3 src/mkversion.py)"
  { echo '%% generated by build.sh (src/mkversion.py); do not edit by hand'
    echo "\\def\\ssversion{${VERSION}}"; } > src/version.tex
  python3 - "$VERSION" <<'PY' || true
import json, os, re, sys
tag = sys.argv[1]
m = re.match(r"v(\d+)v(\d+)i(\d+)", tag)
p = "tracker.json"
if m and os.path.exists(p):
    d = json.load(open(p, encoding="utf-8"))
    d.setdefault("current", {}).update(
        {"volume": int(m.group(1)), "version": int(m.group(2)),
         "iteration": int(m.group(3)), "tag": tag})
    with open(p, "w", encoding="utf-8") as fh:
        json.dump(d, fh, indent=2)
        fh.write("\n")
PY
  echo "[0/4] version: ${VERSION}  (config.toml + folder '$(basename "$PWD")')"
  echo "      editions this run: ${PAPERS[*]}"

  # --- preprocess once: the manuscript is shared by every edition ------------
  echo "[1/4] preprocess: ${NAME}.md -> ${TEMP}/vol1_latex.md"
  python3 src/preprocess.py

  # --- build each requested edition from that one intermediate ---------------
  for paper in "${PAPERS[@]}"; do
    build_one "$paper"
  done

  # --- step 4: self-healing recovery archive ---------------------------------
  # Keep <folder>.zip a faithful, current snapshot of every source plus the built
  # PDF(s): everything except temp/ and the archive itself. ARCHIVE_ITEMS lists
  # src and outputs, so the generated src/paper.tex and whichever PDFs now sit in
  # outputs/ are captured automatically. "zip -FS" file-syncs: it adds new files,
  # refreshes changed ones, and drops entries whose files are gone, so a missing
  # or stale archive is brought back into agreement on every build. The loose PDF
  # in outputs/ can then be deleted and recovered from here, and if a rebuild ever
  # fails this archive still holds the PDF and the exact code that generated it.
  ARCHIVE_ITEMS=(build.sh config.toml tracker.json README.md HANDOVER.md MANIFEST.md
                 sovereign-stack-vol1.md src assets outputs)
  [ -f "$ARCHIVE" ] && state="refreshed" || state="created"
  zip -FS -r -q "$ARCHIVE" "${ARCHIVE_ITEMS[@]}" -x '*/__pycache__/*' -x '*/.DS_Store'
  n=$(unzip -l "$ARCHIVE" | tail -1 | awk '{print $2}')
  echo "[4/4] recovery archive ${ARCHIVE}: ${state} (${n} files; temp/ and the archive excluded)"

  echo "Done -> outputs/   (build trail kept in ${TEMP}/; verify: python3 src/tests/test_build.py)"
} 2>&1 | tee "${TEMP}/build.log"
